version: "3.5"

networks:
  intra:
    driver: bridge
    attachable: false
 # front-network:
  #  driver: bridge
 #   attachable: false
 # back-network:
 #   driver: bridge
 #   attachable: false

volumes:
  mdb-data:
  wordpress:

services:

  nginx:
    depends_on:
      - wordpress-php
    build: "./services/nginx"
    image: nginx:mytag
    container_name: nginx
    volumes:
      - wordpress:/var/www/myserver/wordpress:rw
      - "../logs/nginx_logs:/var/log/nginx:rw"
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 9000
    networks:
      - intra
     # - front-network


  wordpress-php:
    depends_on:
      - mariadb
    build: "./services/wordpress"
    image: wordpress-php:mytag
    container_name: wordpress-php
    volumes:
      - wordpress:/var/www/myserver/wordpress:rw
      - "../logs/php-fpm_logs/php7.3-fpm.log:/var/log/php7.3-fpm.log:rw"
    restart: on-failure
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_NAME=wordpress
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - NGINX_SERVER=nginx:9000
    expose:
      - 3306
      - 9000
    networks:
      - intra
     # - front-network
     # - back-network


  mariadb:
    build: "./services/mariadb"
    image: mariadb:mytag
    container_name: mariadb
    volumes:
      - mdb-data:/var/lib/mysql:rw
      - "../logs/mariadb_logs/error.log:/var/log/mysql/error.log"
    restart: on-failure
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_USER_PASSWORD=wordpress
      - MYSQL_ROOT_PASSWORD=root
    expose:
      - 3306
    networks:
      intra:
        aliases:
          - mariadb
     # - back-network


   #env_file: .env-local
# add secrets for pw!








#Usage:
#docker-compose [-f <arg>...] [--profile <name>...] [options] [COMMAND] [ARGS...]
#docker-compose -h|--help

#Options:
#  -f, --file FILE             Specify an alternate compose file
#                              (default: docker-compose.yml)
#  -p, --project-name NAME     Specify an alternate project name
#                              (default: directory name)
#Commands:
#  build              Build or rebuild services
#  bundle             Generate a Docker bundle from the Compose file
#  config             Validate and view the Compose file
#  create             Create services
#  down               Stop and remove containers, networks, images, and volumes
#  events             Receive real time events from containers
#  exec               Execute a command in a running container
#  help               Get help on a command
#  images             List images
#  kill               Kill containers
#  logs               View output from containers
#  pause              Pause services
#  port               Print the public port for a port binding
#  ps                 List containers
#  pull               Pull service images
#  push               Push service images
#  restart            Restart services
#  rm                 Remove stopped containers
#  run                Run a one-off command
#  scale              Set number of containers for a service
#  start              Start services
#  stop               Stop services
#  top                Display the running processes
#  unpause            Unpause services
#  up                 Create and start containers
#  version            Show the Docker-Compose version information
